### ISSUE TITLE
Updating Order not stored in MongoDB

### ISSUE THREAD

**Issue by gstester** [MassTransit/Sample-Twitch#2]
Hi,
I am trying to use your example as a basis for a new project. As I understand to MongoRepo should store the current Orderstate of an order. But looking into MongoDB after submitting the same order with different customerNumber I can't see the new cardNumber in MongoDB. Only the version is incremented.
Have I change something in configuration to solvee this?

Any help is appreciated.

Regards Gerd

**Comment by phatboyg** [comment]
Subsequent order submissions are ignored, you'd need to accept that event in this state to update the card number, but at that point the order is already being processed. Now, if the order had faulted and was in a faulted state, you could accept the submission again with a new card number and reprocess the routing slip.

https://github.com/MassTransit/Sample-Twitch/blob/master/src/Sample.Components/StateMachines/OrderStateMachine.cs#L49

**Comment by gstester** [comment]
THX.
It was my fault not to look to the '??=' operator in OrderSubmitted.
